"""Org phone primary keys

Revision ID: 0d3dde932640
Revises: e699427f077f
Create Date: 2025-10-22 00:54:26.429261

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d3dde932640'
down_revision: Union[str, Sequence[str], None] = 'e699427f077f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('organization_phones', 'organization_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index(op.f('ix_organization_phones_id'), table_name='organization_phones')
    op.drop_column('organization_phones', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organization_phones', sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_organization_phones_id'), 'organization_phones', ['id'], unique=False)
    op.alter_column('organization_phones', 'organization_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
