"""change organization_phones primary key

Revision ID: e699427f077f
Revises: 3d3d70e31558
Create Date: 2025-10-22 00:30:39.524608

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e699427f077f'
down_revision: Union[str, Sequence[str], None] = '3d3d70e31558'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organization_phones', sa.Column('id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_organization_phones_id'), 'organization_phones', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_organization_phones_id'), table_name='organization_phones')
    op.drop_column('organization_phones', 'id')
    # ### end Alembic commands ###
